version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    env_file:
      - config/config.env
    # ports:
    #   - "${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}"
    volumes:
      - ./mongodb:/data/db
    # TODO: add auth

  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: python3 bot/bot.py
    restart: always
    env_file:
      - config/config.env
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo
    volumes:
      - ./:/code/

  mongo_express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    env_file:
      - config/config.env
    # ports:
    #   - "${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=chatgpt_telegram_bot
      - ME_CONFIG_BASICAUTH_USERNAME=mongo_user
      - ME_CONFIG_BASICAUTH_PASSWORD=!!!123qweASD!!!
    depends_on:
      - mongo